// <auto-generated />
using System;
using Inventario.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventario.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231222170926_conexionInventario")]
    partial class conexionInventario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inventario.Models.Dispositivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Bienes_nacionales")
                        .HasColumnType("int");

                    b.Property<string>("Cod_inventario")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Estado")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("Fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Modelo")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Nombre_equipo")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Propietario_equipo")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Serial_no")
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Dispositivos");
                });
#pragma warning restore 612, 618
        }
    }
}
